:set number
:set relativenumber
:set ignorecase
:set smartcase
:set clipboard=unnamedplus
:set path+=**
:colorscheme lunaperche
":colorscheme wildcharm
":colorscheme desert
:set cursorline
:set list
:set scrolloff=8
:set sidescrolloff=8
:set tabstop=4
:set softtabstop=4
:set shiftwidth=4
:set expandtab
:set nowrap
